# Generated by Django 4.2.29 on 2026-04-12 14:56

from django.db import migrations, models
import web.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='user/photos/default.png', upload_to=web.models.user.photo_upload_to),
        ),
    ]
